import { useState } from 'react';
import './LandingPage.css';

function LandingPage({ onGetStarted }) {
  const [activeSection, setActiveSection] = useState('home');
  const heroImage = '/conceptify-ai.jpg';

  return (
    <div className="landing-page">

      {/* Navigation */}
      <nav className="landing-nav">
        <div className="nav-container">
          <div className="logo">Conceptify AI</div>
          <div className="nav-links">
            <a href="#home" className={activeSection === 'home' ? 'active' : ''} onClick={() => setActiveSection('home')}>Home</a>
            <a href="#features" className={activeSection === 'features' ? 'active' : ''} onClick={() => setActiveSection('features')}>Key Features</a>
            <a href="#how-it-works" className={activeSection === 'how' ? 'active' : ''} onClick={() => setActiveSection('how')}>How It Works</a>
            <a href="#architecture" className={activeSection === 'arch' ? 'active' : ''} onClick={() => setActiveSection('arch')}>Architecture</a>
          </div>
          <button className="get-started-btn" onClick={onGetStarted}>Get Started</button>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="dv-hero-section" id="home">
        <div className="dv-hero-content">

          {/* Floating Assets */}
          <img src="/asset_notepad.png" alt="Notepad and pencil" className="dv-asset dv-asset-notepad" />
          <img src="/asset_paintbrush.png" alt="Paintbrush" className="dv-asset dv-asset-paintbrush" />
          <img src="/asset_question.png" alt="Glowing question mark" className="dv-asset dv-asset-question" />
          <img src="/asset_pencil.png" alt="Large Pencil" className="dv-asset dv-asset-main-pencil" />

          <h1 className="dv-main-title">VISUALIZE</h1>

          <div className="dv-hero-text">
            <p className="dv-subtitle">EVERY <span className="italic-serif">doubt</span> NEEDS <span className="italic-serif">a picture</span></p>
            <p className="dv-tagline">Transforming ambiguity into CLARITY</p>
          </div>

          <div className="dv-badge">
            <svg viewBox="0 0 100 100" className="dv-badge-bg">
              <polygon points="50,0 60,10 75,5 80,20 95,20 95,35 100,50 95,65 95,80 80,80 75,95 60,90 50,100 40,90 25,95 20,80 5,80 5,65 0,50 5,35 5,20 20,20 25,5 40,10" fill="#FF8C00" />
            </svg>
            <div className="dv-badge-content">
              <span>CONCEPTIFY</span>
              <strong>VISUAL<br />LEAGUE</strong>
              <span>2026</span>
              <div className="dv-badge-icons">📈 📊</div>
            </div>
          </div>

        </div>
      </section>



      {/* Features Section */}
      <section className="features-section" id="features">
        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon-image">
              <img src="/voice-input.jpg.jpeg" alt="Voice Input" />
            </div>
            <h3>Voice-Powered Tutor</h3>
            <p>Ask your questions via voice or text, receive explanations in a natural, spoken voice</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon-image">
              <img src="/ai-powered-explanation.jpg.jpeg" alt="AI Powered" />
            </div>
            <h3>AI-Powered Explanations</h3>
            <p>Receive clear, simplified explanations and real-life analogies generated by Amazon Nova</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon-image">
              <img src="/interactive-learning.jpg" alt="Interactive Learning" />
            </div>
            <h3>Interactive Learning</h3>
            <p>Engage with personalized practice questions to test your understanding</p>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="how-it-works-section" id="how-it-works">
        <h2 className="section-title">How Conceptify AI Works</h2>
        <p className="section-subtitle">
          Three simple steps to go from doubt to clarity. No complex setup or prior knowledge required - just ask and learn.
        </p>
        <div className="workflow-diagram">
          <div className="workflow-step">
            <div className="step-icon user-icon">
              <img src="/user.jpg" alt="User" className="workflow-icon-img" />
            </div>
            <div className="step-label">User</div>
            <p className="step-description">Ask your question</p>
          </div>

          <div className="workflow-arrow">→</div>

          <div className="workflow-step">
            <div className="step-icon backend-icon">
              <img src="/backend.jpg" alt="Backend" className="workflow-icon-img" />
            </div>
            <div className="step-label">Backend</div>
            <p className="step-description">Process with AI</p>
          </div>

          <div className="workflow-arrow">→</div>

          <div className="workflow-step">
            <div className="step-icon nova-icon">
              <img src="/nova.jpg" alt="Nova AI" className="workflow-icon-img" />
            </div>
            <div className="step-label">Nova</div>
            <p className="step-description">Generate explanation</p>
          </div>

          <div className="workflow-arrow">→</div>

          <div className="workflow-step">
            <div className="step-icon response-icon">
              <img src="/response.jpg" alt="Response" className="workflow-icon-img" />
            </div>
            <div className="step-label">Response</div>
            <p className="step-description">Get clear answer</p>
          </div>
        </div>
      </section>

      {/* Architecture Section */}
      <section className="architecture-section" id="architecture">
        <h2 className="section-title">Built with Modern Technology</h2>
        <div className="tech-stack">
          <div className="tech-item">
            <div className="tech-badge">⚛️</div>
            <span>React 18</span>
          </div>
          <div className="tech-item">
            <div className="tech-badge">🟢</div>
            <span>Node.js</span>
          </div>
          <div className="tech-item">
            <div className="tech-badge">☁️</div>
            <span>AWS S3</span>
          </div>
          <div className="tech-item">
            <div className="tech-badge">🤖</div>
            <span>Amazon Nova</span>
          </div>
          <div className="tech-item">
            <div className="tech-badge">🔐</div>
            <span>JWT Auth</span>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta-section">
        <div className="cta-content">
          <h2>Ready to Transform Your Learning?</h2>
          <p>Join thousands of students who are learning smarter, not harder</p>
          <button className="cta-button" onClick={onGetStarted}>Start Learning Now</button>
        </div>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <div className="footer-content">
          <div className="footer-section">
            <h4>Conceptify AI</h4>
            <p>Your Educational Tutor to Success</p>
          </div>
          <div className="footer-section">
            <h4>Features</h4>
            <ul>
              <li>Voice Input</li>
              <li>AI Explanations</li>
              <li>Practice Questions</li>
              <li>Learning History</li>
            </ul>
          </div>
          <div className="footer-section">
            <h4>Resources</h4>
            <ul>
              <li>Documentation</li>
              <li>GitHub</li>
              <li>Support</li>
            </ul>
          </div>
        </div>
        <div className="footer-bottom">
          <p>© 2026 Conceptify AI. Built with ❤️ for education.</p>
        </div>
      </footer>
    </div>
  );
}

export default LandingPage;
